name: Kubernetes Deployment

on:
  workflow_call:
    inputs:
      HELM_RELEASE_NAME:
        description: Helm release name
        required: true
        type: string
      HELM_CHART_PATH:
        description: Path to the Helm chart directory
        required: true
        type: string
      EKS_CLUSTER_NAME:
        description: EKS Cluster Name
        required: true
        type: string
      IMAGE_REPOSITORY:
        description: Docker image repository
        required: true
        type: string
      IMAGE_TAG:
        description: Docker image tag
        required: true
        type: string
      APP_NAME:
        description: Application Name
        required: true
        type: string
        default: "java-web-app"
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      AWS_REGION:
        required: true
      ECR_REPOSITORY:
        required: true
      ECR_REPOSITORY_URL:
        required: true
      ROLE_NAME:
        description: Role name to assume
        required: true
  

  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ inputs.EKS_CLUSTER_NAME }} \
            --alias eks-cluster

      - name: Verify Cluster
        run: kubectl get nodes

      - name: Clone Helm Chart Repository
        run: |
          git clone --branch main https://github.com/madnansystems87/helm-deployment.git
          echo "Cloned Helm Chart Repository"

      - name: Navigate to Helm Chart Directory
        working-directory: ./helm-deployment/${{ inputs.HELM_CHART_PATH }}
        run: |
          echo "Navigated to Helm Chart Directory"

      - name: Deploy Using Helm
        working-directory: ./helm-deployment/${{ inputs.HELM_CHART_PATH }}
        run: |
          helm upgrade --install ${{ inputs.HELM_RELEASE_NAME }} ./ \
            --set image.repository=${{ secrets.ECR_REPOSITORY_URL }} \
            --set image.tag=${{inputs.APP_NAME}}-${{ inputs.IMAGE_TAG }}

      - name: Wait for Pods to be Ready
        run: |
          kubectl wait --for=condition=ready pod --all --timeout=120s

      - name: Get Pod Status
        run: kubectl get pods --namespace default